// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOpZyIky2KOuigBRQY3v-b80aRFO23VY',
    appId: '1:869441306004:web:af9957172d8087783b2381',
    messagingSenderId: '869441306004',
    projectId: 'directorios-sinaloa',
    authDomain: 'directorios-sinaloa.firebaseapp.com',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuy9oKoeql2zVWvB0lQWB9v02acs_hwnA',
    appId: '1:869441306004:android:1e8bf7a3365dec303b2381',
    messagingSenderId: '869441306004',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOeiuUgL-SJVXxbIkm4ihu6HZsXMK_p0',
    appId: '1:869441306004:ios:c65256f8374c264d3b2381',
    messagingSenderId: '869441306004',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
    iosBundleId: 'com.example.directoriossinaloa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOeiuUgL-SJVXxbIkm4ihu6HZsXMK_p0',
    appId: '1:869441306004:ios:c65256f8374c264d3b2381',
    messagingSenderId: '869441306004',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
    iosBundleId: 'com.example.directoriossinaloa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfOpZyIky2KOuigBRQY3v-b80aRFO23VY',
    appId: '1:869441306004:web:a391b1ea51173fc53b2381',
    messagingSenderId: '869441306004',
    projectId: 'directorios-sinaloa',
    authDomain: 'directorios-sinaloa.firebaseapp.com',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );
}
