// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiP8RsarDcwrTByYK06IFjGwRDzHBF7ns',
    appId: '1:339700507997:web:424bff5203fa403157b4b4',
    messagingSenderId: '339700507997',
    projectId: 'directorios-sinaloa',
    authDomain: 'directorios-sinaloa.firebaseapp.com',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFoqdsGkNnkuzHHpalRfnlIHOEGFGUP7s',
    appId: '1:339700507997:android:c04b1b107ab8e22c57b4b4',
    messagingSenderId: '339700507997',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3ymizwdqxvBj16-Dp315QN1R7ZhywQk',
    appId: '1:339700507997:ios:cf45214e4d9474a157b4b4',
    messagingSenderId: '339700507997',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
    iosBundleId: 'com.example.directoriossinaloa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3ymizwdqxvBj16-Dp315QN1R7ZhywQk',
    appId: '1:339700507997:ios:cf45214e4d9474a157b4b4',
    messagingSenderId: '339700507997',
    projectId: 'directorios-sinaloa',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
    iosBundleId: 'com.example.directoriossinaloa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiP8RsarDcwrTByYK06IFjGwRDzHBF7ns',
    appId: '1:339700507997:web:aafdbcc1ceb08b5a57b4b4',
    messagingSenderId: '339700507997',
    projectId: 'directorios-sinaloa',
    authDomain: 'directorios-sinaloa.firebaseapp.com',
    storageBucket: 'directorios-sinaloa.firebasestorage.app',
  );
}
