// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-ynTEJ9Stp4w14TBqGl8tj1qel7dMO4',
    appId: '1:943018463993:web:dd0c125c5087a005530828',
    messagingSenderId: '943018463993',
    projectId: 'directorios-laguna',
    authDomain: 'directorios-laguna.firebaseapp.com',
    storageBucket: 'directorios-laguna.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZswvyHei8V4iMR6oIyT9I9yau3S37X0',
    appId: '1:943018463993:android:622059b326a77390530828',
    messagingSenderId: '943018463993',
    projectId: 'directorios-laguna',
    storageBucket: 'directorios-laguna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1KjNd-qOUHdKUrTFQUjSwW684-JaYynA',
    appId: '1:943018463993:ios:d2363ce7ea45795c530828',
    messagingSenderId: '943018463993',
    projectId: 'directorios-laguna',
    storageBucket: 'directorios-laguna.firebasestorage.app',
    iosBundleId: 'com.example.directoriosLaguna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1KjNd-qOUHdKUrTFQUjSwW684-JaYynA',
    appId: '1:943018463993:ios:d2363ce7ea45795c530828',
    messagingSenderId: '943018463993',
    projectId: 'directorios-laguna',
    storageBucket: 'directorios-laguna.firebasestorage.app',
    iosBundleId: 'com.example.directoriosLaguna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-ynTEJ9Stp4w14TBqGl8tj1qel7dMO4',
    appId: '1:943018463993:web:da8937f643d66b0c530828',
    messagingSenderId: '943018463993',
    projectId: 'directorios-laguna',
    authDomain: 'directorios-laguna.firebaseapp.com',
    storageBucket: 'directorios-laguna.firebasestorage.app',
  );
}
