name: Despliegue Automático a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Compilar y Subir Web
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código de GitHub
        uses: actions/checkout@v4

      - name: 2. Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 3. Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 🔑 4. Compila Flutter desactivando el Service Worker para evitar caché vieja
      - name: 4. Compilar la aplicación para Web
        run: flutter build web --release --pwa-strategy=none

      # 🚀 5. Subida estable por FTP (Cero bloqueos de SSH / Cero Timeouts)
      - name: 5. Subir archivos mediante FTP
        uses: SamKirsch/ftp-deploy@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: ./public_html/
          dangerous-clean-slate: false