name: Despliegue Automático a Hostinger

on:
  push:
    branches:
      - main # 👈 El robot SOLO se activará cuando mandes cambios a la rama main

jobs:
  web-deploy:
    name: Compilar y Subir Web
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código de GitHub
        uses: actions/checkout@v4

      - name: 2. Instalar Java (Requisito de Flutter)
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 3. Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 4. Compilar la aplicación para Web
        run: flutter build web --release

      - name: 5. Subir los archivos por FTP a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: build/web/
          server-dir: ./public_html/
