name: Despliegue Automático a Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Compilar y Subir Web
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código de GitHub
        uses: actions/checkout@v4

      - name: 2. Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 3. Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 4. Compilar la aplicación para Web
        run: flutter build web --release

      - name: 5. Subir archivos mediante RSync/SSH Key
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlptgozr --delete"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SOURCE: "build/web/"
          TARGET: "/home/u492244081/domains/medicosdurango.com/public_html/"
          SCRIPT_AFTER: |
            chmod -R 755 /home/u492244081/domains/medicosdurango.com/public_html/
